layout_spectrum: 0.3471178
color:
  saturation: 0.5137845
  lightness: 0.3132832
  brandStrength: 0.758772
  brandColors:
    - '#313030'
    - '#786F65'
    - '#F3CFBD'
    - '#FBAB65'
    - '#396F49'
  rhythmicContrast: 0.6159148
typography_spectrum: 0.8088973
name: MuseScenic
